tag: &tag

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
version: 2.1
jobs:
  create_pull_request:
    docker:
        - image: circleci/golang:1.11-stretch
    steps:
      - checkout
      - run:
          name: Install hub command
          command: |
            curl -sSLf https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz | \
            tar zxf - --strip-components=1 -C /tmp/ && \
            sudo mv /tmp/bin/hub /usr/local/bin/hub
      - run:
          name: Replace image definition
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            sed -i -e 's/\(gitops-sample:\)[0-9\.]\+.*$/\10.0.2/g' infra/default/application.yaml
      - run:
          name: Create a pull request
          command: |
            git config --global user.name "pm11"
            git config --global user.email "shinichiro.tdk+github@gmail.com"
            git checkout --no-track -b sample
            git commit -m 'sample'
            git add infra/default/application.yaml
            hub push origin sample
            cd ${CIRCLE_WORKING_DIRECTORY}
            hub pull-request --message="test" --base=${CIRCLE_PROJECT_USERNAME}:sample --head=${CIRCLE_PROJECT_USERNAME}:master

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: gitops-sample
          tag: 0.0.2
      - create_pull_request

